### ISSUE TITLE
oneclient version: 3.0.0-rc11-43-gfeb6b50 core-dumped

### ISSUE THREAD

**Issue by caifti** [indigo-dc/oneclient#1]
It seems that there are problems between OneClient v. 3.0.0-rc11-43-gfeb6b50, .deb package for Ubuntu14.04, instaleld from INDIGO repository and Oneprovider 3.0.0-rc11, docker container installed:
+ oneclient -V
oneclient version: 3.0.0-rc11-43-gfeb6b50
FUSE library version: 2.9
+ export PROVIDER_HOSTNAME=oneprovider.cloud.cnaf.infn.it
+ export ONECLIENT_AUTHORIZATION_TOKEN=MDAxNWxvY2...F021ARu4bAK
+ mkdir -p onedata_test
+ oneclient --no_check_certificate --authentication token /home/jenkins/onedata_test
Connecting to provider 'oneprovider.cloud.cnaf.infn.it' ...
Segmentation fault (core dumped)

This can be seen also in the Ci-Jenkins job: https://jenkins.indigo-datacloud.eu:8080/job/oneclient-install/18/platform=bubuntu14/console.

**Comment by groundnuty** [comment]
From what I remember we managed to solve that.
